# -*- coding: utf-8 -*-
names_to_hex = {
    # Non-colour CSS values
    #'transparent':          'transparent',
    #'inherit':              'inherit',
    # Primary Palette
    'pink':                  '#fff1e0',
    'black':                 '#000000',
    'white':                 '#ffffff',
    'blue':                  '#2e6e9e',
    'dark-blue':             '#275e86',
    'claret':                '#9e2f50',
    'orange':                '#d66d06',
    'grey-tint1':            '#b0b0b0',
    'grey-tint2':            '#999999',
    'grey-tint3':            '#777777',
    'grey-tint4':            '#505050',
    'grey-tint5':            '#333333',
    'pink-tint1':            '#f6e9d8',
    'pink-tint2':            '#e9decf',
    'pink-tint3':            '#cec6b9',
    'pink-tint4':            '#a7a59b',
    'pink-tint5':            '#74736c',
    # Colours
    'red':                   '#cc0000',
    'green':                 '#458b00',
    # Highlight tints
    'orange-tint1':          '#eda45e',
    'brown-tint1':           '#94826b',
    'yellow-tint1':          '#eed485',
    'green-tint1':           '#a6a471',
    'bluegreen-tint1':       '#819e9a',
    'silver-tint1':          '#c1b8b4',
    'purple-tint1':          '#936971',
    'purple-tint2':          '#737e7e',
    'red-tint1':             '#b1493f',
    'red-tint2':             '#c36256',
    'red-tint3':             '#d17c70',
    'red-tint4':             '#df9c92',
    'red-tint5':             '#ebbcb3',
    'blue-tint1':            '#598caf',
    'blue-tint2':            '#75a5c2',
    'blue-tint3':            '#8ab5cd',
    'blue-tint4':            '#a9cadc',
    'blue-tint5':            '#bcd7e5',
    # Sections colours
    'section-purple':        '#92288f',
    'section-light-purple':  '#ebcaec',
    'section-blue':          '#0e6dcc',
    'section-light-blue':    '#c5d4e8',
    'section-green':         '#09a25c',
    'section-light-green':   '#a1dbb2',
    'section-red':           '#cc0033',
    # Next
    # http://next.ft.com/__styleguide/design-primitives#palette
    'warm-1':                '#ffe9d7',
    'warm-2':                '#f6e9d8',
    'warm-3':                '#cec6b9',
    'warm-4':                '#1d1d1d',
    'cold-1':                '#505050',
    'cold-2':                '#333333',
    'cold-3':                '#1d1d1d',
    'red-1':                 '#c00d00',
    'red-2':                 '#f99d9d',
    'blue-1':                '#002758',
    'blue-2':                '#eeeeee',
    'purple-1':              '#410057',
    'purple-2':              '#f3dee3',
    'link-1':                '#27757b',
    'link-2':                '#2bbbbf'
}
